/*CREATE TABLE test2 (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID，自增',
    `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '姓名',
    age INT NOT NULL DEFAULT 0 COMMENT '年龄',
    email VARCHAR(100) NOT NULL DEFAULT '' COMMENT '邮箱地址',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) COMMENT='测试表2'*/
DROP TABLE `testai`.`test2`;
