--
-- Schema Sync 0.9.4 Patch Script
-- Created: Thu, Jul 02, 2026
-- Server Version: 5.7.44
-- Apply To: 192.168.0.164/nginxui
--

USE `nginxui`;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE `audit_logs` ( `id` bigint(20) NOT NULL AUTO_INCREMENT, `user_id` int(11) NOT NULL , `username` varchar(50) NOT NULL , `operation_type` varchar(50) NOT NULL , `resource_type` varchar(50) DEFAULT NULL , `resource_id` int(11) DEFAULT NULL , `operation_desc` varchar(500) DEFAULT NULL , `request_params` json DEFAULT NULL , `ip_address` varchar(15) DEFAULT NULL , `user_agent` varchar(500) DEFAULT NULL , `status` enum('success','failure') DEFAULT 'success' , `error_message` text , `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`), KEY `idx_user_id` (`user_id`), KEY `idx_operation_type` (`operation_type`), KEY `idx_created_at` (`created_at`), KEY `idx_resource` (`resource_type`,`resource_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;
CREATE TABLE `cert_deployment` ( `id` int(11) NOT NULL AUTO_INCREMENT, `certificate_id` int(11) NOT NULL, `target_type` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL, `target_id` int(11) NOT NULL, `cert_remote_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `key_remote_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `fullchain_remote_path` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `last_deploy_at` timestamp NULL DEFAULT NULL, `last_deploy_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `last_deploy_message` text COLLATE utf8mb4_unicode_ci, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `uk_cert_target` (`certificate_id`,`target_type`,`target_id`), KEY `idx_cert_id` (`certificate_id`), CONSTRAINT `fk_deploy_cert` FOREIGN KEY (`certificate_id`) REFERENCES `ssl_certificates` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cert_notification_log` ( `id` int(11) NOT NULL AUTO_INCREMENT, `certificate_id` int(11) NOT NULL, `notify_type` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL, `sent_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `recipient` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `subject` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL, `status` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT 'sent', `error_message` text COLLATE utf8mb4_unicode_ci, PRIMARY KEY (`id`), KEY `idx_cert_notify` (`certificate_id`,`notify_type`,`sent_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `config_templates` ( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `description` text COLLATE utf8mb4_unicode_ci, `content` text COLLATE utf8mb4_unicode_ci NOT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `dns_credentials` ( `id` int(11) NOT NULL AUTO_INCREMENT, `provider` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'aliyun', `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `credential_key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `credential_secret` text COLLATE utf8mb4_unicode_ci NOT NULL, `region` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT '', `description` text COLLATE utf8mb4_unicode_ci, `is_default` tinyint(1) DEFAULT '0', `extra_config` json DEFAULT NULL, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_provider` (`provider`), KEY `idx_name` (`name`), KEY `idx_is_default` (`is_default`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `schema_migrations` ( `id` int(11) NOT NULL AUTO_INCREMENT, `filename` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL, `applied_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `execution_time_ms` int(11) DEFAULT '0', PRIMARY KEY (`id`), UNIQUE KEY `filename` (`filename`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ssl_certificate_logs` ( `id` int(11) NOT NULL AUTO_INCREMENT, `certificate_id` int(11) NOT NULL, `action` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `status` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL, `message` text COLLATE utf8mb4_unicode_ci, `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_cert_id` (`certificate_id`), KEY `idx_created_at` (`created_at`), CONSTRAINT `fk_cert_log_cert` FOREIGN KEY (`certificate_id`) REFERENCES `ssl_certificates` (`id`) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `system_settings` ( `id` int(11) NOT NULL AUTO_INCREMENT, `setting_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL , `setting_value` text COLLATE utf8mb4_unicode_ci , `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL , `updated_by` int(11) DEFAULT NULL , `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `setting_key` (`setting_key`), KEY `idx_setting_key` (`setting_key`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ;
DROP TABLE `aliyun_credentials`;
ALTER TABLE `nginx_config_versions` ADD COLUMN `created_by` int(11) NULL AFTER `content`, ADD INDEX `idx_config_version` (`host_id`, `file_path`, `created_at`) USING BTREE;
ALTER TABLE `nginx_hosts` ADD COLUMN `host_key` varchar(512) NULL AFTER `description`, ADD COLUMN `cert_dir` varchar(512) NULL AFTER `updated_at`;
ALTER TABLE `ssl_certificates` ADD COLUMN `dns_provider` varchar(50) NULL DEFAULT 'aliyun' AFTER `domain`, ADD COLUMN `dns_credential_key` varchar(255) NULL AFTER `fullchain_path`, ADD COLUMN `dns_credential_secret` text NULL AFTER `dns_credential_key`, ADD COLUMN `source_type` varchar(20) NULL DEFAULT 'manual' AFTER `description`, DROP COLUMN `aliyun_access_key_id`, DROP COLUMN `aliyun_access_key_secret`, ADD INDEX `idx_dns_provider` (`dns_provider`) USING BTREE, ADD INDEX `idx_source_type` (`source_type`) USING BTREE, ADD INDEX `idx_cert_renewal` (`auto_renew`, `status`, `expires_at`) USING BTREE;
ALTER TABLE `users` ADD COLUMN `last_login_at` timestamp NULL AFTER `is_active`, ADD COLUMN `login_count` int(11) NULL DEFAULT '0' AFTER `last_login_at`;
SET FOREIGN_KEY_CHECKS = 1;
CREATE VIEW `aliyun_credentials` AS select `dns_credentials`.`id` AS `id`,`dns_credentials`.`name` AS `name`,`dns_credentials`.`credential_key` AS `access_key_id`,`dns_credentials`.`credential_secret` AS `access_key_secret`,`dns_credentials`.`region` AS `region`,`dns_credentials`.`description` AS `description`,`dns_credentials`.`is_default` AS `is_default`,`dns_credentials`.`created_at` AS `created_at`,`dns_credentials`.`updated_at` AS `updated_at` from `dns_credentials` where (`dns_credentials`.`provider` = 'aliyun');
